### ISSUE TITLE
URL in hint of SHACL related properties leads to namespace page of SHACL

### ISSUE THREAD

**Issue by k00ni** [faubulous/mentor-vscode#41] opened 2024-10-31 13:59 UTC
Offtopic: **Great extension!**

---

When hovering a SHACL property (such as `sh:closed`) it shows a hint with an URL. This URL always leads me to the namespace page of SHACL as you can see below.

![Bildschirmfoto vom 2024-10-31 14-52-20](https://github.com/user-attachments/assets/11c22083-2761-4d06-8898-29b244c4becf)

Is that intended behavior or did you rather mean a page such as the following?

![Bildschirmfoto vom 2024-10-31 14-57-51](https://github.com/user-attachments/assets/02d942bf-f265-4357-a66f-08141a518c29)

In the current version the URL provides no real value even though the hint itself is very helpful for SHACL beginners.

**Comment by faubulous** [comment] 2024-10-31 20:25
Dear @k00ni,

thank you for your support and for taking the time to write such a detailed report! This is highly appreciated. If you like Mentor then you could support me by writing a review or leaving a rating in the VSCode Marketplace. 🙂

---

**Regarding your topic:** 

Unfortunately I cannot fix this because it is not a bug in Mentor. The problem is that the W3C namespace URL for SHACL is not resolvable. Other URLs such as the namespace for SKOS, on the other hand, are: [skos:Concept](https://www.w3.org/2009/08/skos-reference/skos.html#Concept). The namespace for W3C is out of my control and I cannot provide a generic solution for this.

It is a pitty that the many of the W3C vocabularies such as OWL, RDFS, SHACL and XSD have no support for content-negotiation and cannot provide browsers with a HTML rendered version of the vocabulary. There does not seem to be a generic infrastructure for publishing vocabularies at the W3C. In this regard, they are unfortunately not following their [own best practices](https://www.w3.org/TR/swbp-vocab-pub/). The W3C *should* change this if they're serious about Linked Data.

OWL, RDFS and XSD at least provide a serialized version of the vocabulary while SHACL leads into a totally useless page, I agree. I would kindly ask you to raise this issue with the SHACL working group at W3C or the [editors on this page](https://www.w3.org/TR/shacl/). Maybe you can ask them to fix it as this is definitively an unhappy practice as you nicely laid out.

I'm closing this issue as I cannot provide a general solution for the problem. We've been building a semantic web of dead links in the past and I can only hope that this will change some time in the future.

**Closed by faubulous** 2024-10-31 20:25 UTC

**Comment by k00ni** [comment] 2024-11-01 06:25
No problem.

I opened an issue as you suggested and asked the editors about it: https://github.com/w3c/shacl/issues/87
